<?php
/**
 * Copyright © 2023 imsafu. All rights reserved.
 * See LICENSE for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Imsafu\Payment\Block\Form
 */
?>
<?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
<div class="items <?php /* @noEscape */ echo $methodCode ?> instructions agreement checkout-agreement-item-content" id="payment_form_<?php /* @noEscape */ echo $methodCode ?>" style="display: none;">
    <?php /* @noEscape */ echo nl2br($block->escapeHtml($instructions)) ?>
    <div style="padding:10px 15px 15px;">
        <img src="<?php $block->escapeUrl($block->getViewFileUrl('Imsafu_Payment::icon_accepted_cryptocurrencies_payment.gif'));?>" alt="<?php echo __('Payment by cryptocurrency'); ?>"><br>
    </div>
</div>
