<?php
/**
 * Copyright © 2023 imsafu. All rights reserved.
 * See LICENSE for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Imsafu\Payment\Block\Info
 */
?>

<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->getInfo()->getLastTransId() == ''): ?>
    <br /><?php echo __('No transaction ID recorded.') ?>
<?php else: ?>
    <br /><?php echo __('imsafu Transaction ID: %1', $this->escapeHtml($block->getInfo()->getLastTransId())) ?>
<?php endif; ?>
